[package]
name = "rrule-dst-bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
iana-time-zone = "0.1.60"
rrule = "0.13.0"
tz-rs = "0.6.14"
